const TEXTOS = {
    es: {
        codigo: "ES",
        login: "Login",
        registro: "Registro",
        email: "Email",
        nick: "Nick",
        contrasena: "Contraseña",
        recordarme: "Recuerdame",
        olvidaste: "¿Olvidaste la contraseña?",
        recuperar: "Recuperar",
        noRegistrado: "¿No estas registrado aún?",
        creaCuenta: "Crea una cuenta",
        entrar: "Entrar",
        yaTienes: "¿Ya tienes cuenta?",
        iniciaSesion: "Inicia sesión",
        crearCuenta: "Crear cuenta",
        usuarios: "Usuarios",
        refrescar: "Refrescar",
        cerrarSesion: "Cerrar sesión",
        eliminar: "Eliminar",
        eliminarCuenta: "Eliminar cuenta",
        cambiarTema: "Cambiar tema",
        cambiarIdioma: "Cambiar idioma",
        dictar: "Dictar",
        verContrasena: "Mostrar contraseña",
        ocultarContrasena: "Ocultar contraseña",
        cuentaCreada: "Cuenta creada. Ya puedes iniciar sesión",
        sesionCerrada: "Sesión cerrada",
        cuentaEliminada: "Tu cuenta ha sido eliminada",
        sesionCaducada: "Tu sesión ha caducado. Vuelve a iniciar sesión",
        confirmarEliminar: "¿Eliminar al usuario {email}?",
        recuperarTitulo: "Recuperar contraseña",
        continuar: "Continuar",
        nuevaContrasenaTitulo: "Nueva contraseña",
        nuevaContrasena: "Nueva contraseña",
        confirmarContrasena: "Repite la contraseña",
        guardarContrasena: "Guardar contraseña",
        volverInicio: "Volver al inicio",
        introduceNuevaContrasena: "Escribe la nueva contraseña",
        contrasenaActualizada: "Contraseña actualizada. Ya puedes iniciar sesión",
        contrasenasNoCoinciden: "Las contraseñas no coinciden",
        vozNoDisponible: "El dictado por voz no está disponible en este navegador",
    },
    en: {
        codigo: "EN",
        login: "Login",
        registro: "Sign up",
        email: "Email",
        nick: "Nick",
        contrasena: "Password",
        recordarme: "Remember me",
        olvidaste: "Forgot your password?",
        recuperar: "Recover",
        noRegistrado: "Don't have an account yet?",
        creaCuenta: "Create an account",
        entrar: "Sign in",
        yaTienes: "Already have an account?",
        iniciaSesion: "Sign in",
        crearCuenta: "Create account",
        usuarios: "Users",
        refrescar: "Refresh",
        cerrarSesion: "Log out",
        eliminar: "Delete",
        eliminarCuenta: "Delete account",
        cambiarTema: "Toggle theme",
        cambiarIdioma: "Change language",
        dictar: "Dictate",
        verContrasena: "Show password",
        ocultarContrasena: "Hide password",
        cuentaCreada: "Account created. You can sign in now",
        sesionCerrada: "Session closed",
        cuentaEliminada: "Your account has been deleted",
        sesionCaducada: "Your session has expired. Sign in again",
        confirmarEliminar: "Delete user {email}?",
        recuperarTitulo: "Reset password",
        continuar: "Continue",
        nuevaContrasenaTitulo: "New password",
        nuevaContrasena: "New password",
        confirmarContrasena: "Repeat the password",
        guardarContrasena: "Save password",
        volverInicio: "Back to sign in",
        introduceNuevaContrasena: "Enter the new password",
        contrasenaActualizada: "Password updated. You can sign in now",
        contrasenasNoCoinciden: "Passwords do not match",
        vozNoDisponible: "Voice dictation is not available in this browser",
    },
};

function aplicarTextos(raiz, textos) {
    raiz.querySelectorAll("[data-texto]").forEach((nodo) => {
        const valor = textos[nodo.dataset.texto];
        if (valor) {
            nodo.textContent = valor;
        }
    });
    raiz.querySelectorAll("[data-etiqueta]").forEach((nodo) => {
        const valor = textos[nodo.dataset.etiqueta];
        if (valor) {
            nodo.setAttribute("aria-label", valor);
        }
    });
}
